package account;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests registration, authentication, validation, and current-player behavior for AccountService.
 *
 * @author Sahtra Green
 * @version 0.1.0
 * @since 8/10/2026
 */
class AccountServiceTest {

    private static final String USERNAME = "playerone";
    private static final String PASSWORD = "secret1";

    private PlayerDAO playerDAO;
    private AccountService accountService;

    @BeforeEach
    void setUp() throws SQLException {
        String databaseUrl = "jdbc:h2:mem:account_"
                + UUID.randomUUID()
                + ";DB_CLOSE_DELAY=-1";

        try (Connection connection = DriverManager.getConnection(databaseUrl);
             Statement statement = connection.createStatement()) {

            statement.execute("""
                    CREATE TABLE player (
                        player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(255) NOT NULL UNIQUE,
                        password_hash VARCHAR(255) NOT NULL,
                        currency_balance INTEGER NOT NULL DEFAULT 0,
                        experience INTEGER NOT NULL DEFAULT 0,
                        active_cat_id INTEGER,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
        }

        playerDAO = new PlayerDAO(databaseUrl);
        accountService = new AccountService(playerDAO);
    }

    @Test
    void register() throws SQLException {
        assertTrue(playerDAO.findByUsername(USERNAME).isEmpty());

        accountService.register(USERNAME, PASSWORD, PASSWORD);

        Optional<Player> result = playerDAO.findByUsername(USERNAME);
        assertTrue(result.isPresent());

        Player createdPlayer = result.orElseThrow();

        assertNotNull(createdPlayer.getPlayerId());
        assertEquals(USERNAME, createdPlayer.getUsername());

        assertNotNull(createdPlayer.getPasswordHash());
        assertFalse(createdPlayer.getPasswordHash().isBlank());
        assertNotEquals(PASSWORD, createdPlayer.getPasswordHash());
        assertTrue(PasswordHasher.matches(PASSWORD, createdPlayer.getPasswordHash()));

        assertEquals(0, createdPlayer.getCurrencyBalance());
        assertEquals(0, createdPlayer.getExperience());
        assertNull(createdPlayer.getActiveCatId());
    }

    @Test
    void usernameValidation() throws SQLException {
        IllegalArgumentException blank = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.register("   ", PASSWORD, PASSWORD)
        );
        assertEquals("Username is required.", blank.getMessage());

        IllegalArgumentException invalidCharacters = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.register("player-one", PASSWORD, PASSWORD)
        );
        assertEquals(
                "Username may only contain letters, numbers, and underscores.",
                invalidCharacters.getMessage()
        );

        IllegalArgumentException tooShort = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.register("ab", PASSWORD, PASSWORD)
        );
        assertEquals(
                "Username must be between 3 and 20 characters.",
                tooShort.getMessage()
        );

        IllegalArgumentException tooLong = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.register(
                        "abcdefghijklmnopqrstu",
                        PASSWORD,
                        PASSWORD
                )
        );
        assertEquals(
                "Username must be between 3 and 20 characters.",
                tooLong.getMessage()
        );

        assertTrue(playerDAO.findByUsername("player-one").isEmpty());
        assertTrue(playerDAO.findByUsername("ab").isEmpty());
        assertTrue(playerDAO.findByUsername("abcdefghijklmnopqrstu").isEmpty());
    }

    @Test
    void passwordValidation() throws SQLException {
        assertTrue(playerDAO.findByUsername(USERNAME).isEmpty());

        IllegalArgumentException blank = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.register(USERNAME, "   ", "   ")
        );
        assertEquals("Password is required.", blank.getMessage());

        IllegalArgumentException tooShort = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.register(USERNAME, "12345", "12345")
        );
        assertEquals(
                "Password must be between 6 and 64 characters.",
                tooShort.getMessage()
        );

        String longPassword = "a".repeat(65);

        IllegalArgumentException tooLong = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.register(USERNAME, longPassword, longPassword)
        );
        assertEquals(
                "Password must be between 6 and 64 characters.",
                tooLong.getMessage()
        );

        assertTrue(playerDAO.findByUsername(USERNAME).isEmpty());
    }

    @Test
    void mismatchedPasswords() throws SQLException {
        assertTrue(playerDAO.findByUsername(USERNAME).isEmpty());

        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.register(USERNAME, PASSWORD, "different1")
        );

        assertEquals("Passwords do not match.", exception.getMessage());
        assertTrue(playerDAO.findByUsername(USERNAME).isEmpty());
    }

    @Test
    void duplicateUsername() throws SQLException {
        assertTrue(playerDAO.findByUsername(USERNAME).isEmpty());

        accountService.register(USERNAME, PASSWORD, PASSWORD);

        Player original = playerDAO.findByUsername(USERNAME).orElseThrow();
        Integer originalId = original.getPlayerId();
        String originalHash = original.getPasswordHash();

        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.register(
                        "  PLAYERONE  ",
                        "differentPassword",
                        "differentPassword"
                )
        );

        assertEquals("That username is already taken.", exception.getMessage());

        Player stored = playerDAO.findByUsername(USERNAME).orElseThrow();

        assertEquals(originalId, stored.getPlayerId());
        assertEquals(originalHash, stored.getPasswordHash());
        assertTrue(PasswordHasher.matches(PASSWORD, stored.getPasswordHash()));
        assertFalse(PasswordHasher.matches("differentPassword", stored.getPasswordHash()));
    }

    @Test
    void usernameNormalization() throws SQLException {
        assertTrue(playerDAO.findByUsername(USERNAME).isEmpty());

        accountService.register("  PlAyErOnE  ", PASSWORD, PASSWORD);

        assertTrue(playerDAO.findByUsername("PlayerOne").isEmpty());

        Player storedPlayer = playerDAO.findByUsername(USERNAME).orElseThrow();

        assertEquals(USERNAME, storedPlayer.getUsername());
        assertTrue(accountService.getCurrentPlayer().isEmpty());

        Player authenticated = accountService.authenticate("  PLAYERONE  ", PASSWORD);

        assertEquals(USERNAME, authenticated.getUsername());
        assertEquals(storedPlayer.getPlayerId(), authenticated.getPlayerId());

        assertTrue(accountService.getCurrentPlayer().isPresent());
        assertEquals(
                authenticated.getPlayerId(),
                accountService.getCurrentPlayer().orElseThrow().getPlayerId()
        );
    }

    @Test
    void authenticate() throws SQLException {
        accountService.register(USERNAME, PASSWORD, PASSWORD);

        Player stored = playerDAO.findByUsername(USERNAME).orElseThrow();

        assertTrue(accountService.getCurrentPlayer().isEmpty());

        Player authenticated = accountService.authenticate(USERNAME, PASSWORD);

        assertNotNull(authenticated);
        assertEquals(stored.getPlayerId(), authenticated.getPlayerId());
        assertEquals(stored.getUsername(), authenticated.getUsername());
        assertEquals(stored.getPasswordHash(), authenticated.getPasswordHash());

        Optional<Player> currentPlayer = accountService.getCurrentPlayer();

        assertTrue(currentPlayer.isPresent());
        assertEquals(
                authenticated.getPlayerId(),
                currentPlayer.orElseThrow().getPlayerId()
        );
    }

    @Test
    void invalidCredentials() throws SQLException {
        accountService.register(USERNAME, PASSWORD, PASSWORD);

        Player before = playerDAO.findByUsername(USERNAME).orElseThrow();
        Integer originalId = before.getPlayerId();
        String originalHash = before.getPasswordHash();

        assertTrue(accountService.getCurrentPlayer().isEmpty());

        IllegalArgumentException missingUser = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.authenticate("missingplayer", PASSWORD)
        );
        assertEquals(
                "Invalid username or password. Please try again.",
                missingUser.getMessage()
        );

        assertTrue(accountService.getCurrentPlayer().isEmpty());

        IllegalArgumentException wrongPassword = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.authenticate(USERNAME, "wrongpassword")
        );
        assertEquals(
                "Invalid username or password. Please try again.",
                wrongPassword.getMessage()
        );

        assertTrue(accountService.getCurrentPlayer().isEmpty());

        Player after = playerDAO.findByUsername(USERNAME).orElseThrow();

        assertEquals(originalId, after.getPlayerId());
        assertEquals(originalHash, after.getPasswordHash());
        assertTrue(playerDAO.findByUsername("missingplayer").isEmpty());
    }

    @Test
    void blankLogin() throws SQLException {
        accountService.register(USERNAME, PASSWORD, PASSWORD);

        Player stored = playerDAO.findByUsername(USERNAME).orElseThrow();

        assertTrue(accountService.getCurrentPlayer().isEmpty());

        IllegalArgumentException blankUsername = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.authenticate("   ", PASSWORD)
        );
        assertEquals(
                "Please enter credentials to continue.",
                blankUsername.getMessage()
        );

        assertTrue(accountService.getCurrentPlayer().isEmpty());

        IllegalArgumentException blankPassword = assertThrows(
                IllegalArgumentException.class,
                () -> accountService.authenticate(USERNAME, "   ")
        );
        assertEquals(
                "Please enter credentials to continue.",
                blankPassword.getMessage()
        );

        assertTrue(accountService.getCurrentPlayer().isEmpty());

        Player after = playerDAO.findByUsername(USERNAME).orElseThrow();

        assertEquals(stored.getPlayerId(), after.getPlayerId());
        assertEquals(stored.getPasswordHash(), after.getPasswordHash());
    }

    @Test
    void logout() throws SQLException {
        accountService.register(USERNAME, PASSWORD, PASSWORD);

        Player authenticated = accountService.authenticate(USERNAME, PASSWORD);

        assertTrue(accountService.getCurrentPlayer().isPresent());
        assertEquals(
                authenticated.getPlayerId(),
                accountService.getCurrentPlayer().orElseThrow().getPlayerId()
        );

        accountService.logout();

        assertTrue(accountService.getCurrentPlayer().isEmpty());

        Player storedPlayer = playerDAO.findByUsername(USERNAME).orElseThrow();

        assertEquals(authenticated.getPlayerId(), storedPlayer.getPlayerId());
        assertEquals(authenticated.getPasswordHash(), storedPlayer.getPasswordHash());
    }
}