package account;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests CRUD operations, queries, constraints, and persistence for PlayerDAO.
 *
 * @author Sahtra Green
 * @version 0.1.0
 * @since 8/3/2026
 */

class PlayerDAOTest {

    private static final String USERNAME = "PlayerOne";
    private static final String PASSWORD_HASH = "hashed-password";

    private PlayerDAO playerDAO;
    private Player player;
    private String databaseUrl;

    @BeforeEach
    void setUp() throws SQLException {
        databaseUrl = "jdbc:h2:mem:player_"
                + UUID.randomUUID()
                + ";DB_CLOSE_DELAY=-1";

        try (Connection connection = DriverManager.getConnection(databaseUrl);
             Statement statement = connection.createStatement()) {

            statement.execute("""
                    CREATE TABLE player (
                        player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(255) NOT NULL UNIQUE,
                        password_hash VARCHAR(255) NOT NULL,
                        currency_balance INTEGER NOT NULL DEFAULT 100,
                        active_cat_id INTEGER,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                        CREATE TABLE cats (
                        cat_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        player_id INTEGER NOT NULL,
                        cat_data VARCHAR(1000) NOT NULL,
                        FOREIGN KEY (player_id) REFERENCES player(player_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE battle (
                        battle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        player_id INTEGER NOT NULL,
                        FOREIGN KEY (player_id) REFERENCES player(player_id)
                    )
                    """);

            statement.execute("""
                    CREATE TABLE player_inventory (
                        player_id INTEGER NOT NULL,
                        item_id INTEGER NOT NULL,
                        quantity INTEGER NOT NULL,
                        PRIMARY KEY (player_id, item_id),
                        FOREIGN KEY (player_id) REFERENCES player(player_id)
                    )
                    """);
        }

        playerDAO = new PlayerDAO(databaseUrl);
        player = new Player(USERNAME, PASSWORD_HASH);
    }

    @Test
    void create() throws SQLException {
        assertTrue(playerDAO.findByUsername(USERNAME).isEmpty());

        Player createdPlayer = playerDAO.create(player);

        assertNotNull(createdPlayer.getPlayerId());
        assertEquals(USERNAME, createdPlayer.getUsername());
        assertEquals(PASSWORD_HASH, createdPlayer.getPasswordHash());
        assertEquals(100, createdPlayer.getCurrencyBalance());
        assertNull(createdPlayer.getActiveCatId());

        Player storedPlayer = playerDAO.findById(createdPlayer.getPlayerId()).orElseThrow();

        assertEquals(createdPlayer.getPlayerId(), storedPlayer.getPlayerId());
        assertEquals(USERNAME, storedPlayer.getUsername());
        assertEquals(PASSWORD_HASH, storedPlayer.getPasswordHash());
        assertEquals(100, storedPlayer.getCurrencyBalance());
        assertNull(storedPlayer.getActiveCatId());
        assertNotNull(storedPlayer.getCreatedAt());

        Player customizedPlayer = new Player("CustomPlayer", "custom-hash");
        customizedPlayer.setCurrencyBalance(500);
        customizedPlayer.setActiveCatId(12);

        Player createdCustomPlayer = playerDAO.create(customizedPlayer);
        Player storedCustomPlayer =
                playerDAO.findById(createdCustomPlayer.getPlayerId()).orElseThrow();

        assertNotEquals(createdPlayer.getPlayerId(), createdCustomPlayer.getPlayerId());
        assertEquals("CustomPlayer", storedCustomPlayer.getUsername());
        assertEquals("custom-hash", storedCustomPlayer.getPasswordHash());
        assertEquals(500, storedCustomPlayer.getCurrencyBalance());
        assertEquals(12, storedCustomPlayer.getActiveCatId());
    }

    @Test
    void find() throws SQLException {
        Player createdPlayer = playerDAO.create(player);

        Player foundById = playerDAO.findById(createdPlayer.getPlayerId()).orElseThrow();

        assertEquals(createdPlayer.getPlayerId(), foundById.getPlayerId());
        assertEquals(USERNAME, foundById.getUsername());
        assertEquals(PASSWORD_HASH, foundById.getPasswordHash());

        Player foundByUsername = playerDAO.findByUsername(USERNAME).orElseThrow();

        assertEquals(createdPlayer.getPlayerId(), foundByUsername.getPlayerId());
        assertEquals(USERNAME, foundByUsername.getUsername());
        assertEquals(PASSWORD_HASH, foundByUsername.getPasswordHash());

        assertTrue(playerDAO.findById(9999).isEmpty());
        assertTrue(playerDAO.findByUsername("MissingPlayer").isEmpty());
    }

    @Test
    void update() throws SQLException {
        Player createdPlayer = playerDAO.create(player);
        Integer playerId = createdPlayer.getPlayerId();

        Player before = playerDAO.findById(playerId).orElseThrow();

        assertEquals(USERNAME, before.getUsername());
        assertEquals(PASSWORD_HASH, before.getPasswordHash());
        assertEquals(100, before.getCurrencyBalance());
        assertNull(before.getActiveCatId());

        createdPlayer.setUsername("UpdatedUsername");
        createdPlayer.setPasswordHash("updated-hash");
        createdPlayer.setCurrencyBalance(250);
        createdPlayer.setActiveCatId(12);

        assertTrue(playerDAO.update(createdPlayer));

        Player after = playerDAO.findById(playerId).orElseThrow();

        assertEquals(playerId, after.getPlayerId());
        assertEquals("UpdatedUsername", after.getUsername());
        assertEquals("updated-hash", after.getPasswordHash());
        assertEquals(250, after.getCurrencyBalance());
        assertEquals(12, after.getActiveCatId());

        createdPlayer.setCurrencyBalance(400);
        createdPlayer.setActiveCatId(null);

        assertTrue(playerDAO.update(createdPlayer));

        Player afterSecondUpdate = playerDAO.findById(playerId).orElseThrow();

        assertEquals(playerId, afterSecondUpdate.getPlayerId());
        assertEquals("UpdatedUsername", afterSecondUpdate.getUsername());
        assertEquals("updated-hash", afterSecondUpdate.getPasswordHash());
        assertEquals(400, afterSecondUpdate.getCurrencyBalance());
        assertNull(afterSecondUpdate.getActiveCatId());

        Player unsavedPlayer = new Player("UnsavedPlayer", "unsaved-hash");

        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> playerDAO.update(unsavedPlayer)
        );

        assertEquals(
                "Cannot update a player without an ID.",
                exception.getMessage()
        );

        Player missingPlayer = new Player("MissingPlayer", "missing-hash");
        missingPlayer.setPlayerId(9999);

        assertFalse(playerDAO.update(missingPlayer));

        Player unchangedPlayer = playerDAO.findById(playerId).orElseThrow();

        assertEquals(400, unchangedPlayer.getCurrencyBalance());
        assertNull(unchangedPlayer.getActiveCatId());
    }

    @Test
    void deleteAccount() throws SQLException {
        Player createdPlayer = playerDAO.create(player);
        int playerId = createdPlayer.getPlayerId();

        try (Connection connection = DriverManager.getConnection(databaseUrl);
             Statement statement = connection.createStatement()) {

            statement.executeUpdate("""
                    INSERT INTO cats (player_id, cat_data)
                    VALUES (%d, 'TestCat')
                    """.formatted(playerId));

            statement.executeUpdate("""
                    INSERT INTO battle (player_id)
                    VALUES (%d)
                    """.formatted(playerId));

            statement.executeUpdate("""
                    INSERT INTO player_inventory (player_id, item_id, quantity)
                    VALUES (%d, 1, 3)
                    """.formatted(playerId));
        }

        assertTrue(playerDAO.findById(playerId).isPresent());

        assertTrue(playerDAO.deleteAccount(playerId));

        assertTrue(playerDAO.findById(playerId).isEmpty());
        assertTrue(playerDAO.findByUsername(USERNAME).isEmpty());

        try (Connection connection = DriverManager.getConnection(databaseUrl);
             Statement statement = connection.createStatement()) {

            try (var resultSet = statement.executeQuery(
                    "SELECT COUNT(*) FROM cats WHERE player_id = " + playerId)) {
                assertTrue(resultSet.next());
                assertEquals(0, resultSet.getInt(1));
            }

            try (var resultSet = statement.executeQuery(
                    "SELECT COUNT(*) FROM battle WHERE player_id = " + playerId)) {
                assertTrue(resultSet.next());
                assertEquals(0, resultSet.getInt(1));
            }

            try (var resultSet = statement.executeQuery(
                    "SELECT COUNT(*) FROM player_inventory WHERE player_id = " + playerId)) {
                assertTrue(resultSet.next());
                assertEquals(0, resultSet.getInt(1));
            }
        }

        assertFalse(playerDAO.deleteAccount(playerId));
    }

    @Test
    void createConstraints() throws SQLException {
        Player original = playerDAO.create(player);

        Integer originalId = original.getPlayerId();
        String originalHash = original.getPasswordHash();

        Player duplicatePlayer = new Player(USERNAME, "different-hash");

        assertThrows(
                SQLException.class,
                () -> playerDAO.create(duplicatePlayer)
        );

        assertNull(duplicatePlayer.getPlayerId());

        Player storedAfterDuplicate =
                playerDAO.findByUsername(USERNAME).orElseThrow();

        assertEquals(originalId, storedAfterDuplicate.getPlayerId());
        assertEquals(originalHash, storedAfterDuplicate.getPasswordHash());
        assertNotEquals("different-hash", storedAfterDuplicate.getPasswordHash());

        Player nullUsernamePlayer = new Player(null, PASSWORD_HASH);

        assertThrows(
                SQLException.class,
                () -> playerDAO.create(nullUsernamePlayer)
        );

        assertNull(nullUsernamePlayer.getPlayerId());

        Player storedAfterFailures =
                playerDAO.findByUsername(USERNAME).orElseThrow();

        assertEquals(originalId, storedAfterFailures.getPlayerId());
        assertEquals(USERNAME, storedAfterFailures.getUsername());
        assertEquals(originalHash, storedAfterFailures.getPasswordHash());

        assertTrue(playerDAO.findById(originalId).isPresent());
    }

    @Test
    void persistence() throws SQLException {
        Player createdPlayer = playerDAO.create(player);

        createdPlayer.setCurrencyBalance(300);
        createdPlayer.setActiveCatId(7);

        assertTrue(playerDAO.update(createdPlayer));

        PlayerDAO reconnectedDAO = new PlayerDAO(databaseUrl);

        Player persistedPlayer =
                reconnectedDAO.findById(createdPlayer.getPlayerId()).orElseThrow();

        assertEquals(createdPlayer.getPlayerId(), persistedPlayer.getPlayerId());
        assertEquals(USERNAME, persistedPlayer.getUsername());
        assertEquals(PASSWORD_HASH, persistedPlayer.getPasswordHash());
        assertEquals(300, persistedPlayer.getCurrencyBalance());
        assertEquals(7, persistedPlayer.getActiveCatId());
        assertNotNull(persistedPlayer.getCreatedAt());

        Player foundByUsername =
                reconnectedDAO.findByUsername(USERNAME).orElseThrow();

        assertEquals(persistedPlayer.getPlayerId(), foundByUsername.getPlayerId());
    }
}